# -*- coding: utf-8 -*-
"""CDIA_CD2_2026_e05_p02_docker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13-sM1e0qpWZawpFvSDhvedevGznCgmsd

# Docker para MLOps — Bella Tavola 🐳
## Parte 2: Configurando, orquestrando e refinando

## Como usar este caderno?

Em e05-p01, a API Bella Tavola passou a rodar em um contêiner. Mas ao final, dois problemas ficaram em aberto:

1. O endpoint `/ml/predict` provavelmente falhou — o contêiner não tinha o `HF_TOKEN`.
2. Qualquer dado criado via API desaparecia quando o contêiner era removido.

Esta parte resolve os dois, e vai além: **Bloco 10** — variáveis de ambiente e volumes. **Bloco 11** — Docker Compose para orquestrar API + PostgreSQL + Nginx. **Bloco 12** — refatorar o `Dockerfile` com `.dockerignore`, usuário não-root e multi-stage build.

Todo o trabalho acontece no terminal e no editor. As células de código são referências para estudar e adaptar.

Os gabaritos estão nas células colapsadas logo após cada exercício — tente resolver antes de abrir.

## O que é essencial, recomendado e desafio?

**Essencial:** o mínimo que você precisa conseguir fazer para completar a etapa.

**Recomendado:** amplia a qualidade da solução.

**Desafio 🎯:** aprofunda a solução do ponto de vista de engenharia.

## Pré-requisitos

Antes de começar, confirme que e05-p01 está completo:
"""

# Execute no terminal, na raiz do projeto Bella Tavola:

# 1. O Dockerfile existe?
# ls Dockerfile
# Saída esperada: Dockerfile

# 2. O build funciona?
# docker build -t bella-tavola:v1 .
# Saída esperada: Successfully built (ou: writing image sha256:...)

# 3. A API responde dentro do contêiner?
# docker run -p 8000:8000 --rm bella-tavola:v1 &
# sleep 3
# curl http://localhost:8000/
# Saída esperada: {"restaurante": "Bella Tavola", ...}

# Se qualquer item falhar, volte para e05-p01 antes de continuar.
# Os Blocos 10, 11 e 12 constroem diretamente sobre o Dockerfile do Bloco 9.

"""---

# BLOCO 10 — Variáveis de ambiente e volumes

> **Objetivo:** Passar o `HF_TOKEN` para o contêiner de forma segura e persistir dados com volumes — resolvendo os dois problemas identificados ao final de e05-p01.

## Conceitos-chave do Bloco 10

### Variáveis de ambiente em Docker

Na Semana 3, você configurou `HF_TOKEN` como secret no GitHub Actions e o passou para os steps do pipeline com `env:`. O mesmo problema existe aqui: a API precisa do token para baixar o modelo, mas ele não pode ficar hardcoded na imagem.

Há três formas de passar variáveis de ambiente para um contêiner:

**1. `-e` no `docker run` — para valores pontuais**
```bash
docker run -e HF_TOKEN=hf_abc123 bella-tavola:v1
```

**2. `--env-file` no `docker run` — para múltiplas variáveis**
```bash
docker run --env-file .env bella-tavola:v1
```
O arquivo `.env` tem o formato `CHAVE=VALOR`, uma por linha.

**3. `ENV` no `Dockerfile` — para valores padrão não sensíveis**
```dockerfile
ENV APP_NAME="Bella Tavola"
ENV DEBUG=false
```

**A regra de ouro:** nunca use `ENV` no `Dockerfile` para secrets. O valor fica gravado na imagem e aparece em `docker history minha-imagem`. Qualquer pessoa com acesso à imagem vê o token.

A conexão com o que você já conhece: o `BaseSettings` do Pydantic que você usou no caderno de FastAPI (e02) lê variáveis de ambiente automaticamente. A API já está preparada para receber `HF_TOKEN` dessa forma — você só precisa passá-lo para o contêiner.

### Contêineres são efêmeros — volumes resolvem isso

No Bloco 8, você criou um arquivo dentro de um contêiner e ele desapareceu na próxima execução. Isso é design intencional: o sistema de arquivos do contêiner é descartado quando o contêiner é removido.

Para dados que precisam persistir (banco de dados, uploads, logs), a solução são **volumes** — armazenamento gerenciado pelo Docker, que existe independente do ciclo de vida do contêiner.

Há dois tipos:

| Tipo | Sintaxe | Gerenciado por | Quando usar |
|---|---|---|---|
| **Named volume** | `-v bella-dados:/app/data` | Docker | Dados de produção: banco, uploads. Persiste mesmo sem contêiner associado. |
| **Bind mount** | `-v /caminho/local:/app` | Você | Desenvolvimento: o código local reflete imediatamente no contêiner. |

A diferença prática: um named volume é gerenciado pelo Docker em um local interno do sistema. Um bind mount espelha um diretório específico do seu computador dentro do contêiner.

```
Named volume:
  Docker storage (/var/lib/docker/volumes/bella-dados/)
       ↕  sincronizado
  /app/data dentro do contêiner

Bind mount:
  /Users/voce/projetos/bella-tavola/ (seu diretório real)
       ↕  espelhado
  /app dentro do contêiner
```

## Exercício 10.1 — Passando o HF_TOKEN para o contêiner

**Nível:** Essencial  
**Conceito:** Variáveis de ambiente em contêineres, a regra de não hardcodar secrets.

### Referência

```bash
# Execute na raiz do projeto Bella Tavola

# --- Sem token: observar o erro ---

# Sobe a API sem passar HF_TOKEN
docker run -p 8000:8000 --rm bella-tavola:v1

# Em outro terminal, testa o endpoint de predição:
curl -X POST http://localhost:8000/ml/predict \
  -H "Content-Type: application/json" \
  -d '{"valor_transacao": 150.0, "hora_transacao": 14, \
       "distancia_ultima_compra": 5.0, "tentativas_senha": 1, \
       "pais_diferente": 0}'
# Saída esperada: erro 500 ou mensagem de autenticação falhou
# (o modelo não consegue ser baixado do Hub sem o token)

# Pare o contêiner: Ctrl+C

# --- Com token via -e ---

docker run -p 8000:8000 --rm -e HF_TOKEN=hf_seu_token_aqui bella-tavola:v1

# Teste novamente — agora deve funcionar
curl -X POST http://localhost:8000/ml/predict \
  -H "Content-Type: application/json" \
  -d '{"valor_transacao": 150.0, "hora_transacao": 14, \
       "distancia_ultima_compra": 5.0, "tentativas_senha": 1, \
       "pais_diferente": 0}'
# Saída esperada: {"prediction": 0, "probability": 0.12, "label": "legítimo", ...}

# --- Com token via --env-file ---

# Seu .env já existe (da semana anterior) — verifique:
# cat .env | grep HF_TOKEN
# Deve mostrar: HF_TOKEN=hf_seu_token_aqui

docker run -p 8000:8000 --rm --env-file .env bella-tavola:v1
# Mesmo resultado — mais conveniente para múltiplas variáveis
```

### Sua tarefa

1. Rode o contêiner **sem** o token e anote o erro exato
2. Rode com `-e HF_TOKEN=...` e confirme que `/ml/predict` funciona
3. Rode com `--env-file .env` e confirme o mesmo resultado
4. Responda as perguntas abaixo
"""

# ✏️ Anote:

# Qual foi o erro exato ao rodar sem HF_TOKEN?
# (copie a mensagem dos logs ou do curl)
#

# Esse erro é diferente do que acontecia no CI sem o secret configurado?
# (lembre-se do e04-p03, exercício 5.1)
#

# Por que o .env nunca deve ser commitado no Git?
# (dica: o que aconteceria se um colega clonar o repositório?)
#

# Confirme: o .env está no .gitignore?
# cat .gitignore | grep .env
#

"""<details>
<summary>💡 Gabarito</summary>

```python
# Erro típico sem HF_TOKEN:
# HTTP 500 Internal Server Error
# ou nos logs do contêiner: huggingface_hub.utils._errors.RepositoryNotFoundError
# ou: requests.exceptions.HTTPError: 401 Client Error: Unauthorized
# A causa: load_model tenta fazer hf_hub_download, que precisa autenticar
# quando o repositório é privado — ou mesmo público com rate limiting.

# A diferença em relação ao CI:
# No CI (e04-p03), o erro era na verificação: 'HF_TOKEN não configurado'
# porque o assert falhava antes mesmo de tentar o download.
# Aqui, o assert não existe — a API tenta usar o token e falha na chamada HTTP.
# O mecanismo é diferente mas a causa raiz é a mesma: token ausente.

# Por que não commitar o .env:
# O .env contém HF_TOKEN (e potencialmente senhas de banco, API keys).
# Um colega que clonar o repositório teria acesso a esses valores.
# Se o repositório for público, qualquer pessoa no mundo teria acesso.
# O token do Hugging Face dá acesso de escrita ao seu Hub — incluindo
# apagar ou sobrescrever seus modelos publicados.

# O .env deve estar no .gitignore (linha: .env)
# E em breve também no .dockerignore (Bloco 12) para não entrar na imagem.
```

</details>

## Exercício 10.2 — Persistindo dados com volume

**Nível:** Essencial  
**Conceito:** Named volumes, persistência além do ciclo de vida do contêiner.

### Referência

```bash
# Execute na raiz do projeto Bella Tavola

# Criar um named volume explicitamente (opcional — docker run cria automaticamente)
docker volume create bella-dados

# Rodar a API montando o volume no diretório onde o SQLite fica
# Ajuste /app/data para o caminho onde sua API armazena o banco
docker run -d -p 8000:8000 \
  --env-file .env \
  -v bella-dados:/app/data \
  --name bella-api \
  bella-tavola:v1

# Saída esperada: ID do contêiner em background

# Criar alguns registros via API
curl -X POST http://localhost:8000/pratos \
  -H "Content-Type: application/json" \
  -d '{"nome": "Prato Persistente", "categoria": "massa", "preco": 45.0}'

# Confirmar que existe
curl http://localhost:8000/pratos
# Deve aparecer "Prato Persistente" na lista

# Parar E remover o contêiner
docker stop bella-api
docker rm bella-api

# Confirmar que o contêiner não existe mais
docker ps -a  # bella-api não aparece

# Subir um NOVO contêiner com o MESMO volume
docker run -d -p 8000:8000 \
  --env-file .env \
  -v bella-dados:/app/data \
  --name bella-api-novo \
  bella-tavola:v1

sleep 3

# Verificar os dados
curl http://localhost:8000/pratos
# Saída esperada: "Prato Persistente" ainda está lá!
```

### Sua tarefa

Execute a sequência completa: crie registros, destrua o contêiner, suba um novo com o mesmo volume e verifique que os dados persistem.
"""

# ✏️ Anote:

# Os dados persistiram após recriar o contêiner?
#

# O que teria acontecido sem o -v bella-dados:/app/data?
#

# Agora rode: docker volume ls
# O volume bella-dados aparece mesmo sem nenhum contêiner rodando?
#

# O que acontece com os dados se você rodar: docker volume rm bella-dados?
# (não execute ainda — só responda)
#

"""<details>
<summary>💡 Gabarito</summary>

```python
# Os dados persistem porque o volume é independente do contêiner.
# O contêiner foi destruído, mas o volume continuou existindo no Docker storage.
# O novo contêiner se conectou ao mesmo volume e encontrou os dados lá.

# Sem -v:
# O banco SQLite estaria dentro do sistema de arquivos do contêiner.
# docker rm apaga o contêiner e tudo dentro dele — incluindo o banco.
# Cada novo contêiner começaria com um banco vazio.

# docker volume ls mostra o volume mesmo sem contêiner associado.
# Volumes são cidadãos de primeira classe no Docker — existem independentemente.
# Isso é especialmente importante para bancos de dados:
# você pode atualizar a imagem da aplicação sem perder os dados.

# docker volume rm bella-dados:
# APAGA OS DADOS PERMANENTEMENTE.
# Não há lixeira, não há undo. Os dados do banco somem.
# Por isso docker volume rm deve ser usado com muito cuidado em produção.
# No Bloco 11, veremos que docker compose down -v faz isso automaticamente
# para todos os volumes do Compose — outro comando a usar com cautela.
```

</details>

## Exercício 10.3 — Bind mount para desenvolvimento

**Nível:** Recomendado  
**Conceito:** Desenvolvimento com live reload dentro do contêiner, sem rebuildar a imagem.

### Referência

```bash
# Execute na raiz do projeto Bella Tavola
# $(pwd) retorna o diretório atual — funciona em Linux e macOS
# No Windows PowerShell, use: ${PWD}

# Bind mount: o diretório local é espelhado em /app dentro do contêiner
# --reload: uvicorn reinicia automaticamente ao detectar mudanças nos arquivos
docker run -p 8000:8000 \
  --env-file .env \
  -v $(pwd):/app \
  bella-tavola:v1 \
  uvicorn main:app --host 0.0.0.0 --port 8000 --reload

# Saída esperada: API sobe normalmente
# INFO: Will watch for changes in these directories: ['/app']

# Em outro terminal: altere uma rota em main.py
# Ex: mude a mensagem da rota raiz
# O uvicorn detecta a mudança e reinicia automaticamente:
# INFO: Detected file change in '/app/main.py'
# INFO: Application startup complete.

# Teste sem rebuildar:
curl http://localhost:8000/
# A mensagem nova aparece imediatamente
```

### Sua tarefa

1. Suba a API com bind mount e `--reload`
2. Altere a mensagem da rota `/` no `main.py` e salve
3. Observe o uvicorn recarregar nos logs
4. Confirme a mudança com `curl`
"""

# ✏️ Anote:

# O uvicorn recarregou automaticamente após a mudança?
#

# Você precisou rebuildar a imagem?
#

# Por que o bind mount em desenvolvimento NÃO substitui o COPY . . no Dockerfile?
# (pense no que acontece quando você entrega a imagem para outro ambiente)
#

# Em que situação o bind mount seria problemático em produção?
#

"""<details>
<summary>💡 Gabarito</summary>

```python
# O bind mount não substitui o COPY . . porque:
# Com bind mount, o código existe APENAS no seu computador.
# A imagem em si não tem o código mais recente — tem o que estava lá no build.
# Se você enviar a imagem para o Docker Hub e alguém tentar rodá-la,
# ela vai usar o código do momento do build, não o que está no seu diretório local.
# Em produção, não existe o seu diretório local — só a imagem.

# Problemas do bind mount em produção:
# 1. O código precisa existir no servidor com o caminho exato
# 2. Qualquer mudança acidental no diretório afeta o contêiner em tempo real
# 3. Não é reproduzível: dois servidores com o mesmo diretório em momentos
#    diferentes podem ter comportamentos diferentes
# 4. Derrota o propósito do contêiner: garantir que o ambiente é idêntico
#    em qualquer lugar
#
# Bind mount é uma ferramenta de desenvolvimento. COPY . . é para produção.
```

</details>

## Exercício 10.4 — Inspecionando volumes

**Nível:** Recomendado  
**Conceito:** Gerenciamento de volumes, entender onde os dados ficam fisicamente.

### Referência

```bash
# Execute no terminal

# Listar todos os volumes
docker volume ls
# Saída esperada: lista com bella-dados e outros volumes criados

# Inspecionar detalhes de um volume
docker volume inspect bella-dados
# Saída esperada (JSON):
# [
#   {
#     "Name": "bella-dados",
#     "Driver": "local",
#     "Mountpoint": "/var/lib/docker/volumes/bella-dados/_data",
#     ...
#   }
# ]
# O Mountpoint é onde o Docker armazena os dados no host
# (em macOS/Windows, esse caminho fica dentro da VM do Docker Desktop)

# Remover o volume (apaga os dados permanentemente)
# docker volume rm bella-dados
# ATENÇÃO: não execute se ainda quer os dados

# Remover todos os volumes não utilizados por nenhum contêiner
# docker volume prune
```

### Sua tarefa

Execute `docker volume ls` e `docker volume inspect bella-dados`. Responda:
"""

# ✏️ Anote:

# Qual é o Mountpoint do volume bella-dados?
#

# Se você está no macOS ou Windows, o Mountpoint aponta para dentro
# da VM do Docker Desktop — você não consegue acessar diretamente pelo Finder/Explorer.
# Como você acessaria esses dados se precisasse fazer backup?
#

# Por que docker volume prune é menos perigoso que docker system prune -a,
# mas ainda deve ser usado com cuidado em uma máquina de desenvolvimento?
#

"""<details>
<summary>💡 Gabarito</summary>

```python
# Para acessar dados em volumes no macOS/Windows:
# A forma mais confiável é através de um contêiner auxiliar:
# docker run --rm -v bella-dados:/data alpine tar czf - /data > backup.tar.gz
# Isso cria um contêiner Alpine temporário, monta o volume,
# comprime os dados e redireciona para um arquivo no host.

# Por que docker volume prune ainda é perigoso:
# Ele remove volumes que não estão montados em nenhum contêiner ATIVO.
# Em uma máquina de desenvolvimento, isso inclui volumes de bancos de dados
# cujos contêineres estão parados (mas não removidos) —
# ex: um postgres que você rodou ontem e parou mas não removeu.
# O contêiner ainda existe (docker ps -a mostra), mas está parado.
# docker volume prune vê o volume como "não utilizado" e o remove.
# Resultado: você perde os dados do banco sem querer.
# Sempre verifique o que será removido com: docker volume ls --filter dangling=true
```

</details>

## Erros comuns neste bloco

| Mensagem ou sintoma | Causa provável | Solução |
|---|---|---|
| `401 Unauthorized` ou erro de modelo | `HF_TOKEN` ausente ou inválido | Confirme com `docker run -e HF_TOKEN=... bella-tavola:v1 env \| grep HF` |
| Dados somem após `docker stop` + `docker start` | Contêiner parado e reiniciado — dados persistem. Mas `docker rm` + novo `docker run` sem volume = dados perdidos | Sempre use `-v` para dados que importam |
| `Error response from daemon: invalid mount config` | Caminho do bind mount errado ou inexistente | Confirme que o diretório local existe antes de montar |
| `--reload` não detecta mudanças | Bind mount não foi configurado — o código dentro da imagem não muda | Confirme que `-v $(pwd):/app` está no comando |

## Checklist do Bloco 10

- [ ] Passo o `HF_TOKEN` para o contêiner sem hardcodá-lo na imagem
- [ ] O endpoint `/ml/predict` funciona dentro do contêiner com o token
- [ ] Crio um named volume e verifico que dados persistem após recriar o contêiner
- [ ] Diferencio bind mount de named volume e sei quando usar cada um
- [ ] Sei que `docker volume rm` apaga dados permanentemente

---

# BLOCO 11 — Docker Compose: orquestrando múltiplos serviços

> **Objetivo:** Substituir os múltiplos comandos `docker run` por um `docker-compose.yml` declarativo, e orquestrar API + PostgreSQL + Nginx como um sistema coeso.

## Conceitos-chave do Bloco 11

### O problema que o Compose resolve

Para rodar a API Bella Tavola com banco e proxy reverso, você precisaria de:

```bash
# Criar rede compartilhada
docker network create bella-net

# Subir banco
docker run -d --name db --network bella-net \
  -e POSTGRES_DB=bellatavolada -e POSTGRES_USER=bella -e POSTGRES_PASSWORD=secreta \
  -v bella-pg-data:/var/lib/postgresql/data \
  postgres:15

# Subir API
docker run -d --name api --network bella-net \
  -p 8000:8000 --env-file .env \
  -v bella-dados:/app/data \
  bella-tavola:v1

# Subir Nginx
docker run -d --name nginx --network bella-net \
  -p 80:80 \
  -v $(pwd)/nginx.conf:/etc/nginx/conf.d/default.conf \
  nginx:alpine
```

Três terminais, três comandos, flags longas, rede manual. O Compose substitui tudo isso por um arquivo declarativo e dois comandos: `docker compose up` e `docker compose down`.

### Anatomia do `docker-compose.yml`

Você já conhece YAML do GitHub Actions. A estrutura do Compose segue a mesma lógica de indentação:

```yaml
services:           # cada serviço é um contêiner
  api:              # nome do serviço (também vira o hostname na rede)
    build: .        # constrói a partir do Dockerfile no diretório atual
    ports:
      - "8000:8000" # equivalente ao -p no docker run
    env_file:
      - .env        # equivalente ao --env-file
    volumes:
      - bella-dados:/app/data  # equivalente ao -v
    depends_on:
      - db          # inicia depois do serviço 'db'

  db:
    image: postgres:15  # usa imagem pronta do registry (não build local)
    environment:
      POSTGRES_DB: bellatavolada
      POSTGRES_USER: bella
      POSTGRES_PASSWORD: secreta
    volumes:
      - bella-pg-data:/var/lib/postgresql/data

volumes:            # declara os named volumes usados pelos serviços
  bella-dados:
  bella-pg-data:
```

### `build` vs. `image`

| Chave | Quando usar | Exemplo |
|---|---|---|
| `build: .` | Imagem construída a partir do Dockerfile local | Sua API Bella Tavola |
| `image: postgres:15` | Imagem pronta do registry (Docker Hub) | Bancos, proxies, ferramentas |

### A rede interna do Compose e o hostname dos serviços

O Compose cria automaticamente uma rede privada para todos os serviços. Dentro dessa rede, cada serviço é acessível pelo seu **nome** como hostname.

```
Fora do Compose (seu terminal):
  → API em localhost:8000
  → PostgreSQL em localhost:5432 (se exposto)

Dentro da rede do Compose:
  → API acessa o banco em: postgresql://bella:secreta@db:5432/bellatavolada
                                                          ↑
                                              nome do serviço no compose.yml
  → Nginx acessa a API em: http://api:8000
                                    ↑
                            nome do serviço no compose.yml
```

`localhost` dentro de um contêiner é o próprio contêiner — não o banco, não a API. Essa é a fonte do erro mais comum ao migrar para Compose, e por isso o exercício 11.2 inclui um checkpoint de falha esperada.

### `depends_on` e seus limites

`depends_on` garante que o serviço **inicia** antes — não que está **pronto para aceitar conexões**. Um PostgreSQL pode levar alguns segundos para inicializar após o processo subir. Se a API tentar conectar antes, vai falhar.

Solução completa: `healthcheck` (exercício 11.4). Solução prática imediata: lógica de retry na própria aplicação — tentar conectar várias vezes antes de desistir.

### Comandos Compose essenciais

| Comando | O que faz |
|---|---|
| `docker compose up` | Sobe todos os serviços em foreground (logs visíveis) |
| `docker compose up -d` | Sobe em background (detached) |
| `docker compose down` | Para e remove contêineres e redes. **Preserva volumes.** |
| `docker compose down -v` | Para, remove contêineres, redes **e volumes**. Dados perdidos. |
| `docker compose logs` | Mostra logs de todos os serviços |
| `docker compose logs -f api` | Acompanha logs do serviço `api` em tempo real |
| `docker compose ps` | Lista contêineres gerenciados pelo Compose |
| `docker compose exec api bash` | Abre shell no serviço `api` |
| `docker compose build` | Rebuilda as imagens dos serviços com `build:` |
| `docker compose restart api` | Reinicia apenas o serviço `api` |

## Exercício 11.1 — Compose mínimo: só a API

**Nível:** Essencial  
**Conceito:** Escrever o primeiro `docker-compose.yml`, comparar com o `docker run` equivalente.

### Referência

```yaml
# docker-compose.yml — serviço único
# Salve na raiz do projeto (mesmo nível que o Dockerfile)

services:
  api:
    build: .          # constrói a partir do Dockerfile no diretório atual
    ports:
      - "8000:8000"   # PORTA_HOST:PORTA_CONTAINER
    env_file:
      - .env          # carrega HF_TOKEN e outras variáveis
    volumes:
      - bella-dados:/app/data

volumes:             # declara os volumes usados
  bella-dados:        # sem configuração adicional = volume local padrão
```

```bash
# Execute na raiz do projeto (onde docker-compose.yml está)

# Subir todos os serviços (foreground — logs aparecem no terminal)
docker compose up
# Saída esperada:
# [+] Building ...  (build da imagem)
# [+] Running ...
# bella-tavola-api-1  | INFO: Application startup complete.

# Em outro terminal, testar:
curl http://localhost:8000/
# Saída esperada: resposta JSON da Bella Tavola

# Parar com Ctrl+C no terminal do compose
# ou em outro terminal:
docker compose down
# Saída esperada:
# [+] Running 2/2
#  ✔ Container bella-tavola-api-1  Removed
#  ✔ Network bella-tavola_default  Removed
# (o volume bella-dados foi preservado)
```

### Sua tarefa

1. Crie o arquivo `docker-compose.yml` na raiz do projeto com o conteúdo da referência
2. Execute `docker compose up` e confirme que a API responde
3. Execute `docker compose down` e observe o que foi removido
4. Responda abaixo
"""

# ✏️ Compare os dois equivalentes:

# Comando docker run equivalente ao docker-compose.yml acima:
#

# O que o Compose fez que o docker run não faz automaticamente?
# (pense na rede, no nome do contêiner, na remoção ao dar down)
#

# O volume bella-dados ainda existia após docker compose down?
# Verifique: docker volume ls
#

"""<details>
<summary>💡 Gabarito</summary>

```python
# Equivalente em docker run:
# docker run -p 8000:8000 --env-file .env -v bella-dados:/app/data bella-tavola:v1

# O que o Compose faz além:
# - Cria automaticamente uma rede privada (bella-tavola_default)
#   para isolar os serviços do resto do Docker
# - Nomeia o contêiner automaticamente (bella-tavola-api-1)
# - docker compose down remove o contêiner E a rede (mas preserva volumes)
# - Gerencia dependências entre serviços (depends_on)
# - Permite escalar serviços: docker compose up --scale api=3

# O volume bella-dados PERSISTE após docker compose down.
# Isso é intencional: down para os serviços, mas não apaga dados.
# Para apagar também os volumes: docker compose down -v
# (útil para resetar o ambiente de desenvolvimento do zero)
```

</details>

## Exercício 11.2 — Adicionando PostgreSQL

**Nível:** Essencial  
**Conceito:** Múltiplos serviços, rede interna do Compose, hostname dos serviços — com checkpoint de falha esperada.

### Referência

```yaml
# docker-compose.yml com API + PostgreSQL

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db             # inicia após o serviço db subir
    environment:
      # String de conexão usando o NOME DO SERVIÇO como hostname
      DATABASE_URL: postgresql://bella:secreta@db:5432/bellatavolada
      #                                          ↑
      #                            nome do serviço no compose.yml

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bellatavolada
      POSTGRES_USER: bella
      POSTGRES_PASSWORD: secreta
    volumes:
      - bella-pg-data:/var/lib/postgresql/data

volumes:
  bella-dados:
  bella-pg-data:
```

```bash
# Verificar logs de um serviço específico:
docker compose logs api
docker compose logs db
docker compose logs -f api    # acompanha em tempo real
```

### Checkpoint de falha esperada — `localhost` vs. nome do serviço

**Antes de adaptar a string de conexão**, faça este experimento deliberado:

**Passo 1:** Configure a `DATABASE_URL` da API usando `localhost` como hostname (como faria fora do Docker):

```yaml
# Versão com bug — para observação
environment:
  DATABASE_URL: postgresql://bella:secreta@localhost:5432/bellatavolada
  #                                          ↑
  #                                      ERRADO dentro do Compose
```

**Passo 2:** Suba o Compose e observe os logs:
"""

# Execute no terminal, na raiz do projeto:

# docker compose up -d
# sleep 5
# docker compose logs api

# ✏️ Anote a mensagem de erro exata nos logs da API:
#

# O banco (serviço db) subiu corretamente? Verifique:
# docker compose logs db
#

# Por que a API não consegue se conectar ao banco usando localhost?
# (lembre-se: dentro do contêiner da API, o que é localhost?)
#

# Pare o Compose antes de continuar:
# docker compose down

"""<details>
<summary>💡 Gabarito — falha com localhost</summary>

```python
# Mensagem de erro típica nos logs da API:
# sqlalchemy.exc.OperationalError: (psycopg2.OperationalError)
# connection to server at "localhost" (127.0.0.1), port 5432 failed:
# Connection refused
# ou:
# asyncpg.exceptions.ConnectionRefusedError: Connection refused

# O banco (db) subiu corretamente — os logs mostram:
# LOG: database system is ready to accept connections
# O problema não é o banco — é onde a API está procurando o banco.

# Por que localhost não funciona:
# Dentro do contêiner da API, localhost (127.0.0.1) é o PRÓPRIO contêiner da API.
# Não há PostgreSQL escutando nesse endereço.
# O banco está em um contêiner separado, acessível pelo nome do serviço 'db'
# na rede interna do Compose.
# É como tentar ligar para você mesmo esperando que outra pessoa atenda.
#
# Solução: DATABASE_URL: postgresql://bella:secreta@db:5432/bellatavolada
#                                                     ↑
#                                      nome do serviço = hostname na rede Compose
```

</details>

**Passo 3:** Corrija a `DATABASE_URL` trocando `localhost` por `db`. Rebuilde e suba novamente:
"""

# Execute no terminal:

# docker compose up -d
# sleep 5
# docker compose logs api
# Saída esperada nos logs: INFO: Application startup complete.

# Testar a API:
# curl http://localhost:8000/pratos

# Criar um prato para testar persistência:
# curl -X POST http://localhost:8000/pratos \
#   -H "Content-Type: application/json" \
#   -d '{"nome": "Tagliatelle Compose", "categoria": "massa", "preco": 52.0}'

# Parar e subir novamente (SEM -v):
# docker compose down
# docker compose up -d
# sleep 5
# curl http://localhost:8000/pratos

# ✏️ O prato 'Tagliatelle Compose' ainda estava lá após o restart?
#

# Agora teste com -v:
# docker compose down -v
# docker compose up -d
# sleep 5
# curl http://localhost:8000/pratos

# ✏️ O prato ainda estava lá após down -v?
#

# Por que down -v é perigoso em produção mas útil em desenvolvimento?
#

"""<details>
<summary>💡 Gabarito</summary>

```python
# Após docker compose down (sem -v): dados PERSISTEM.
# O volume bella-pg-data existe independente dos contêineres.
# O banco sobe com os mesmos dados que tinha antes.

# Após docker compose down -v: dados SOMEM.
# -v remove os volumes declarados no compose.yml.
# O banco sobe vazio na próxima vez.

# Por que perigoso em produção:
# Em produção, os volumes contêm dados reais de usuários.
# Um down -v acidental apaga tudo permanentemente.
# Não há undo, não há lixeira.

# Por que útil em desenvolvimento:
# Às vezes você quer começar do zero — banco limpo, schema recriado.
# down -v é o equivalente a "resetar o ambiente".
# É o mesmo motivo pelo qual você usa down -v em testes de integração:
# cada execução começa com estado limpo.
```

</details>

## Exercício 11.3 — Adicionando Nginx como proxy reverso

**Nível:** Recomendado  
**Conceito:** Proxy reverso, por que não expor o uvicorn diretamente na porta 80.

### Por que um proxy reverso?

O uvicorn é excelente para servir a aplicação Python — mas não foi projetado para ser o ponto de entrada público de um sistema. O Nginx atua como a "recepção": recebe todas as requisições externas, lida com SSL, compressão, rate limiting, e distribui o tráfego para a API. A API fica em uma porta interna (8000), não exposta diretamente.

```
Antes:  Usuário → porta 8000 → uvicorn
Depois: Usuário → porta 80  → Nginx → porta 8000 → uvicorn
```

### Referência

```nginx
# nginx.conf — salve na raiz do projeto
# Configuração mínima: proxy reverso para a API

server {
    listen 80;             # Nginx escuta na porta 80

    location / {
        proxy_pass http://api:8000;    # repassa para o serviço 'api' na rede Compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
```

```yaml
# docker-compose.yml atualizado com Nginx

services:
  api:
    build: .
    # Não exponha a porta 8000 para o host — o Nginx é o único ponto de entrada
    # ports: removido intencionalmente
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://bella:secreta@db:5432/bellatavolada

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bellatavolada
      POSTGRES_USER: bella
      POSTGRES_PASSWORD: secreta
    volumes:
      - bella-pg-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"            # Nginx exposto na porta 80 do host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # bind mount do arquivo de config
    depends_on:
      - api

volumes:
  bella-pg-data:
```

```bash
# Execute na raiz do projeto (onde nginx.conf e docker-compose.yml estão)

docker compose up -d
sleep 5

# Testar via Nginx (porta 80 — sem especificar porta na URL)
curl http://localhost/
curl http://localhost/pratos
# Saída esperada: respostas JSON da API chegando via Nginx

# Confirmar que a API não está mais acessível diretamente na porta 8000
curl http://localhost:8000/
# Saída esperada: Connection refused
```

### Sua tarefa

1. Crie o arquivo `nginx.conf` na raiz do projeto
2. Atualize o `docker-compose.yml` adicionando o serviço `nginx` e removendo o `ports` da API
3. Suba o Compose e confirme que a API responde em `http://localhost` (sem porta)
4. Confirme que a porta 8000 não está mais acessível diretamente
"""

# ✏️ Anote:

# A API respondeu em http://localhost (porta 80)?
#

# A porta 8000 ficou inacessível diretamente?
#

# O nginx.conf usa 'api' como hostname para o proxy_pass.
# Por que isso funciona? Quem resolve esse nome?
#

# Em um cenário real de produção, que outras configurações
# você adicionaria ao nginx.conf?
#

"""<details>
<summary>💡 Gabarito</summary>

```python
# O nome 'api' no proxy_pass é resolvido pelo DNS interno do Docker Compose.
# O Compose cria uma rede privada e um servidor DNS interno que mapeia
# nomes de serviços para os IPs internos dos contêineres.
# 'api' → IP do contêiner da API na rede Compose
# Isso funciona porque Nginx está na mesma rede que a API.

# Configurações adicionais para produção no nginx.conf:
# - SSL/TLS (HTTPS): bloco server com listen 443 ssl e certificados
# - Rate limiting: limit_req_zone e limit_req para evitar abuso
# - Compressão: gzip on; para respostas JSON menores
# - Headers de segurança: X-Frame-Options, X-Content-Type-Options
# - Cache de respostas: proxy_cache para endpoints estáticos
# - Timeout: proxy_read_timeout para endpoints lentos (ex: /ml/predict)
```

</details>

## Exercício 11.4 — Desafio: healthcheck e ordem de inicialização 🎯

**Nível:** Desafio  
**Conceito:** O limite do `depends_on`, `healthcheck` com `condition: service_healthy`.

### O problema

`depends_on: db` garante que o contêiner do banco **iniciou** antes da API. Mas o PostgreSQL pode levar 2 a 5 segundos para estar pronto para aceitar conexões após o processo subir. Se a API tentar conectar nesse intervalo, a conexão é recusada e a API pode falhar na inicialização.

### Sua tarefa

Adicione um `healthcheck` ao serviço `db` e configure o `depends_on` da API para aguardar o banco estar saudável:
"""

# ✏️ Implemente no docker-compose.yml:

# O healthcheck usa pg_isready para verificar se o PostgreSQL aceita conexões:
# db:
#   image: postgres:15
#   environment: ...
#   volumes: ...
#   healthcheck:
#     test: ["CMD-SHELL", "pg_isready -U bella -d bellatavolada"]
#     interval: 5s      # verifica a cada 5 segundos
#     timeout: 5s       # timeout de cada verificação
#     retries: 5        # tenta 5 vezes antes de marcar como unhealthy

# E no serviço api, mude o depends_on para:
# api:
#   depends_on:
#     db:
#       condition: service_healthy   # espera o healthcheck passar

# Após implementar:
# docker compose down -v
# docker compose up
# Observe nos logs: a API espera o banco estar healthy antes de iniciar

"""<details>
<summary>💡 Gabarito</summary>

```yaml
# docker-compose.yml com healthcheck

services:
  api:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy   # aguarda o healthcheck do banco
    environment:
      DATABASE_URL: postgresql://bella:secreta@db:5432/bellatavolada

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bellatavolada
      POSTGRES_USER: bella
      POSTGRES_PASSWORD: secreta
    volumes:
      - bella-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bella -d bellatavolada"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s   # dá tempo extra na primeira inicialização

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  bella-pg-data:

# O que você verá nos logs com condition: service_healthy:
# bella-tavola-db-1    | LOG: database system is ready to accept connections
# bella-tavola-api-1   | (só inicia após o healthcheck passar)
# bella-tavola-api-1   | INFO: Application startup complete.
#
# Sem healthcheck, a API pode iniciar enquanto o banco ainda não está pronto,
# tentando conectar e falhando — ou precisando de lógica de retry na aplicação.
```

</details>

## Erros comuns neste bloco

| Mensagem ou sintoma | Causa provável | Solução |
|---|---|---|
| `Connection refused` ao banco | API usando `localhost` em vez do nome do serviço | Veja o checkpoint de falha esperada do 11.2 |
| API falha na inicialização mesmo com `depends_on` | Banco ainda não estava pronto — race condition | Implemente `healthcheck` (exercício 11.4) |
| `bind: address already in use` na porta 80 | Outro processo (ou Nginx) já está na porta 80 | `sudo lsof -i :80` para identificar e parar o conflito |
| Nginx retorna 502 Bad Gateway | A API não está respondendo na porta 8000 | `docker compose logs api` para ver o erro da API |
| Volumes não criados após `docker compose up` | Volumes não declarados na seção `volumes:` raiz | Adicione todos os volumes usados na seção `volumes:` |

## Checklist do Bloco 11

- [ ] Escrevo um `docker-compose.yml` com múltiplos serviços
- [ ] Entendo a diferença entre `build:` e `image:` em um serviço
- [ ] Serviços se comunicam usando o nome do serviço como hostname
- [ ] Sei a diferença entre `docker compose down` e `docker compose down -v`
- [ ] `docker compose up -d` sobe todos os serviços em background
- [ ] A API responde via Nginx em `http://localhost` (porta 80)

---

# BLOCO 12 — Boas práticas: segurança e eficiência

> **Objetivo:** Refatorar o `Dockerfile` com três práticas que resolvem problemas concretos: `.dockerignore` (imagem grande e com arquivos desnecessários), usuário não-root (processo rodando com privilégios excessivos), e multi-stage build (imagem inflada por dependências de build).

## Conceitos-chave do Bloco 12

### `.dockerignore` — o que o `COPY . .` copia sem você perceber

Quando você executa `docker build .`, o Docker envia todo o conteúdo do diretório para o daemon — é o "build context". O `COPY . .` então copia tudo isso para a imagem.

O que provavelmente está no seu diretório que **não deveria estar na imagem de produção**:

```
bella-tavola/
├── __pycache__/        ← bytecode compilado, desnecessário
├── .git/               ← histórico do repositório, pode ser gigante
├── .env                ← secrets! nunca deve entrar na imagem
├── env_ci_test/        ← ambiente virtual, centenas de MB desnecessários
├── model.pkl           ← artefato de ML, baixado do Hub em runtime
├── tests/              ← testes não são necessários em produção
├── *.ipynb             ← cadernos Jupyter, não pertencem à imagem
└── .dockerignore       ← o próprio arquivo (convenção: não copiar)
```

O `.dockerignore` funciona exatamente como o `.gitignore` — mesmo formato, mesma lógica de padrões glob:

```
# .dockerignore
__pycache__
*.pyc
.git
.env
env_ci_test/
*.pkl
tests/
*.ipynb
.dockerignore
```

### Usuário não-root — por que importa

Por padrão, os processos dentro de um contêiner rodam como `root`. Isso é conveniente — não há problemas de permissão — mas é desnecessariamente poderoso.

Se um atacante explorar uma vulnerabilidade na API (ex: injeção de comando via um campo de formulário), ele ganha acesso como `root` dentro do contêiner. Em configurações padrão isso ainda é isolado do host, mas:
- Em alguns setups, `root` no contêiner pode ter acesso a volumes e sockets
- O princípio do menor privilégio diz: dê ao processo apenas o que ele precisa
- A API Bella Tavola só precisa ler arquivos e servir HTTP — não precisa de root

```dockerfile
# Cria usuário e grupo sem privilégios
RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser

# Garante que o usuário tem acesso ao diretório da aplicação
RUN chown -R appuser:appgroup /app

# Troca para o usuário sem privilégios
USER appuser
```

### Multi-stage build — separar build de runtime

O problema: pacotes como `scikit-learn` e `numpy` precisam de compiladores e headers de sistema para instalar — mas esses compiladores não são necessários para **rodar** a API.

Com multi-stage build, você usa dois estágios no mesmo `Dockerfile`:

```dockerfile
# ── Estágio 1: builder ──────────────────────────────────────────
# Tem tudo que é necessário para INSTALAR as dependências
FROM python:3.11-slim AS builder

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt
#                               ↑
#              instala em /install em vez de no sistema — fácil de copiar

# ── Estágio 2: final ────────────────────────────────────────────
# Imagem limpa — sem compiladores, sem cache, sem ferramentas de build
FROM python:3.11-slim

WORKDIR /app

# Copia APENAS os pacotes instalados do estágio builder
COPY --from=builder /install /usr/local

# Copia o código da aplicação
COPY . .

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
```

A imagem final contém apenas Python, os pacotes instalados e o código — sem nenhuma ferramenta de build. O estágio `builder` é usado como intermediário e descartado.

## Exercício 12.1 — Adicionando `.dockerignore`

**Nível:** Essencial  
**Conceito:** Reduzir o build context, proteger secrets, imagem mais limpa.

### Referência

```bash
# Execute na raiz do projeto

# Ver o tamanho atual da imagem
docker images bella-tavola:v1
# Anote o tamanho na coluna SIZE

# Ver o que está na imagem (o que o COPY . . copiou)
docker run --rm bella-tavola:v1 find /app -type f | sort
# Saída: todos os arquivos dentro de /app no contêiner
# Você vai ver __pycache__, .git (se não estava ignorado), etc.

# Template de .dockerignore para projetos Python/FastAPI:
# (crie o arquivo .dockerignore na raiz do projeto)
```

```
# .dockerignore

# Bytecode Python — gerado automaticamente, desnecessário na imagem
__pycache__
*.pyc
*.pyo
*.pyd

# Controle de versão — histórico não pertence à imagem
.git
.gitignore

# Secrets — nunca devem entrar na imagem
.env
*.env

# Ambientes virtuais — centenas de MB desnecessários
env_ci_test/
venv/
.venv/

# Artefatos de ML — baixados do Hub em runtime
*.pkl
*.joblib

# Testes — não pertencem à imagem de produção
tests/
pytest.ini
.pytest_cache/

# Cadernos Jupyter — não pertencem à imagem
*.ipynb
.ipynb_checkpoints/

# O próprio dockerignore (convenção)
.dockerignore
```

### Sua tarefa

1. Anote o tamanho atual da imagem e os arquivos que estão em `/app`
2. Crie o `.dockerignore` com o template acima (adapte ao que existe no seu projeto)
3. Rebuilde a imagem: `docker build -t bella-tavola:v2 .`
4. Compare tamanho e conteúdo
"""

# ✏️ Anote:

# Tamanho da imagem ANTES do .dockerignore (bella-tavola:v1):
#

# Tamanho da imagem DEPOIS do .dockerignore (bella-tavola:v2):
#

# Quais arquivos foram removidos da imagem?
# (compare: docker run --rm bella-tavola:v2 find /app -type f | sort)
#

# O .env ainda estava na imagem v2?
# docker run --rm bella-tavola:v2 find /app -name '.env'
# Saída esperada: nenhuma saída (arquivo não existe na imagem)
#

# A diferença de tamanho foi grande ou pequena? Por que?
# (dica: o que ocupa mais espaço — o código Python ou os pacotes instalados?)
#

"""<details>
<summary>💡 Gabarito</summary>

```python
# A diferença de tamanho geralmente é modesta (decenas de MB, não centenas)
# porque o que ocupa espaço na imagem são os PACOTES instalados pelo pip,
# não o código Python da aplicação (que tem alguns KB a poucos MB).
# scikit-learn + numpy + fastapi + uvicorn = ~800MB a 1.2GB independente do código.

# O principal benefício do .dockerignore não é o tamanho final da imagem,
# mas sim:
# 1. SEGURANÇA: .env não entra na imagem (se a imagem vazar, secrets não vazam)
# 2. VELOCIDADE DE BUILD: contexto menor = menos tempo para enviar ao daemon
# 3. CACHE: mudanças em arquivos ignorados não invalidam o cache de build
# 4. LIMPEZA: imagem de produção contém apenas o que é necessário

# A redução de tamanho real vem do multi-stage build (exercício 12.3),
# que elimina os compiladores e headers usados no pip install.
```

</details>

## Exercício 12.2 — Usuário não-root

**Nível:** Essencial  
**Conceito:** Princípio do menor privilégio aplicado a contêineres.

### Referência

```bash
# Verificar com qual usuário o processo está rodando atualmente
docker run --rm bella-tavola:v2 whoami
# Saída esperada: root

# Verificar o ID do usuário
docker run --rm bella-tavola:v2 id
# Saída esperada: uid=0(root) gid=0(root) groups=0(root)
```

```dockerfile
# Dockerfile atualizado com usuário não-root
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Cria grupo e usuário sem privilégios
# addgroup --system: cria grupo do sistema (sem entrada no /etc/passwd)
# adduser --system: cria usuário do sistema sem senha e sem shell de login
RUN addgroup --system appgroup && \
    adduser --system --ingroup appgroup appuser

# Transfere a propriedade dos arquivos para o novo usuário
RUN chown -R appuser:appgroup /app

# Troca para o usuário sem privilégios
# Todas as instruções seguintes (CMD, ENTRYPOINT) rodam como appuser
USER appuser

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
```

### Sua tarefa

1. Confirme que a imagem atual roda como `root`
2. Adicione a criação de usuário ao `Dockerfile` (após o `COPY . .`)
3. Rebuilde: `docker build -t bella-tavola:v2 .`
4. Verifique que agora roda como `appuser`
5. Confirme que a API ainda funciona
"""

# Execute no terminal:

# Após rebuildar:
# docker run --rm bella-tavola:v2 whoami
# Saída esperada: appuser

# docker run --rm bella-tavola:v2 id
# Saída esperada: uid=999(appuser) gid=999(appgroup) ...
# (o número exato varia)

# Confirmar que a API ainda funciona:
# docker run -p 8000:8000 --rm --env-file .env bella-tavola:v2
# curl http://localhost:8000/

# ✏️ Anote:

# A API ainda funcionou com usuário não-root?
#

# Se houve erro de permissão: qual era e como foi resolvido?
# (o chown -R garante que appuser pode ler os arquivos da aplicação)
#

# Por que a instrução USER deve vir APÓS o pip install?
# O que aconteceria se USER viesse antes?
#

"""<details>
<summary>💡 Gabarito</summary>

```python
# Por que USER vem depois do pip install:
# pip install --no-cache-dir -r requirements.txt instala pacotes em locais
# do sistema como /usr/local/lib/python3.11/site-packages/
# que requerem permissões de root.
# Se USER viesse antes, o pip install falharia com:
# PermissionError: [Errno 13] Permission denied: '/usr/local/lib/...'

# A ordem correta:
# 1. Instalar pacotes (como root)
# 2. Copiar código (como root)
# 3. Criar usuário não-root
# 4. chown: transferir propriedade dos arquivos para o usuário
# 5. USER: trocar para o usuário não-root
# 6. CMD: roda como não-root

# Erros de permissão comuns:
# Se a API cria arquivos em runtime (logs, banco SQLite),
# o diretório precisa ser de propriedade do appuser.
# O chown -R /app resolve para arquivos já presentes.
# Para diretórios criados em runtime, pode ser necessário:
# RUN mkdir -p /app/data && chown appuser:appgroup /app/data
```

</details>

## Exercício 12.3 — Multi-stage build

**Nível:** Recomendado  
**Conceito:** Separar a fase de instalação da fase de execução para reduzir o tamanho da imagem final.

### Referência

```dockerfile
# Dockerfile com multi-stage build + usuário não-root

# ── Estágio 1: builder ──────────────────────────────────────────────────────
# Tem tudo que é necessário para INSTALAR as dependências
# O nome 'builder' é uma convenção — pode ser qualquer nome
FROM python:3.11-slim AS builder

WORKDIR /app

COPY requirements.txt .

# Instala em /install — um diretório separado para facilitar a cópia
# --no-cache-dir: não guarda cache do pip
# --prefix=/install: instala os pacotes em /install em vez de /usr/local
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# ── Estágio 2: final ────────────────────────────────────────────────────────
# Imagem limpa — começa do zero sem nenhum resíduo do builder
FROM python:3.11-slim

WORKDIR /app

# Copia APENAS os pacotes instalados do estágio builder
# --from=builder: instrui o Docker a copiar do estágio anterior
COPY --from=builder /install /usr/local

# Copia o código da aplicação
COPY . .

# Usuário não-root
RUN addgroup --system appgroup && \
    adduser --system --ingroup appgroup appuser && \
    chown -R appuser:appgroup /app

USER appuser

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
```

### Sua tarefa

1. Anote o tamanho atual de `bella-tavola:v2`
2. Atualize o `Dockerfile` para usar multi-stage build
3. Rebuilde: `docker build -t bella-tavola:v3 .`
4. Compare os tamanhos e confirme que a API ainda funciona
"""

# Execute no terminal:

# Comparar tamanhos:
# docker images bella-tavola

# Confirmar que a API v3 funciona:
# docker run -p 8000:8000 --rm --env-file .env bella-tavola:v3
# curl http://localhost:8000/
# curl http://localhost:8000/pratos

# ✏️ Anote:

# Tamanho de bella-tavola:v2 (sem multi-stage):
#

# Tamanho de bella-tavola:v3 (com multi-stage):
#

# Redução percentual aproximada:
#

# A API v3 funcionou normalmente?
#

# O que exatamente foi eliminado da imagem final pelo multi-stage?
# (dica: o que o pip install usa que não é necessário para rodar a API)
#

"""<details>
<summary>💡 Gabarito</summary>

```python
# Redução típica com multi-stage para projetos de ML:
# v2 (sem multi-stage): ~1.1GB a 1.3GB
# v3 (com multi-stage): ~700MB a 900MB
# Redução: 30% a 40%

# O que foi eliminado:
# O estágio builder instala pacotes que requerem compilação.
# Durante o processo, pip baixa e compila código C/C++ (para numpy, scikit-learn).
# Isso deixa no sistema: compiladores (gcc), headers de desenvolvimento,
# arquivos intermediários de compilação, e o próprio cache de download do pip.
# Nenhum desses arquivos é necessário para RODAR a API —
# só para INSTALAR as dependências.
# O multi-stage descarta tudo isso e copia apenas os .py e .so compilados.

# Por que a redução não é maior:
# Os próprios pacotes instalados (os arquivos .so compilados de numpy,
# scikit-learn, etc.) são grandes e ficam na imagem final.
# Eles são necessários em runtime — não há como removê-los.
# A redução viria do .whl cache e das ferramentas de build, não dos pacotes em si.
```

</details>

## Exercício 12.4 — Desafio: análise de layers com `docker history` 🎯

**Nível:** Desafio  
**Conceito:** Inspecionar layers individualmente para identificar o que está ocupando espaço.

### Sua tarefa

Use `docker history` para inspecionar as imagens `v1` e `v3` e responda:
"""

# Execute no terminal:

# Ver as layers da imagem v1
# docker history bella-tavola:v1
# Cada linha é uma instrução do Dockerfile e seu tamanho

# Ver com mais detalhes (sem truncar comandos)
# docker history --no-trunc bella-tavola:v1

# Comparar com v3
# docker history bella-tavola:v3

# ✏️ Responda:

# Qual instrução do Dockerfile ocupa mais espaço em v1?
#

# Em v3, a layer do pip install aparece? Por que?
#

# Qual layer de v3 é a maior? O que você poderia fazer para reduzir?
#

# Bônus: instale a ferramenta 'dive' (https://github.com/wagoodman/dive)
# e use 'dive bella-tavola:v3' para uma análise visual das layers.
# O que a ferramenta mostra que docker history não mostra?
#

"""<details>
<summary>💡 Gabarito</summary>

```python
# Em v1, a maior layer é geralmente o RUN pip install.
# Scikit-learn + numpy + suas dependências somam centenas de MB.

# Em v3, a layer do pip install do estágio builder NÃO aparece.
# O docker history só mostra as layers da imagem FINAL.
# O estágio builder foi descartado — suas layers não existem em v3.
# O que aparece em v3 é o COPY --from=builder /install /usr/local,
# que tem tamanho similar ao pip install mas sem os arquivos intermediários.

# A maior layer de v3 ainda é o COPY --from=builder (os pacotes instalados).
# Para reduzir ainda mais:
# - Remover dependências desnecessárias do requirements.txt
# - Usar versões mais enxutas dos pacotes (ex: scikit-learn sem exemplos)
# - Em casos extremos: compilar os pacotes com stripped binaries
# Na prática, para a Bella Tavola, o tamanho atual é aceitável.

# O 'dive' mostra:
# - Exatamente quais ARQUIVOS foram adicionados/modificados/removidos em cada layer
# - Arquivos desperdiçados (adicionados em uma layer e removidos em outra —
#   ocupam espaço mas não são visíveis)
# - Eficiência da imagem: % do tamanho que é conteúdo útil
# docker history mostra apenas o tamanho total de cada instrução,
# não os arquivos individuais.
```

</details>

## Erros comuns neste bloco

| Mensagem ou sintoma | Causa provável | Solução |
|---|---|---|
| `PermissionError` ao iniciar a API | `USER appuser` antes do `pip install`, ou `chown` não configurado | Mova `USER appuser` para depois do `chown -R` |
| `PermissionError` ao criar arquivos em runtime | Diretório não é de propriedade do `appuser` | Adicione `RUN mkdir -p /app/data && chown appuser /app/data` antes do `USER` |
| Imagem v3 não funciona: `ModuleNotFoundError` | `COPY --from=builder` copiou para caminho errado | Verifique que `/install` e `/usr/local` são compatíveis com a imagem base |
| `.env` ainda aparece na imagem | `.dockerignore` não está na raiz ou tem erro de sintaxe | Verifique com `docker run --rm bella-tavola:v3 find /app -name '.env'` |

## Checklist do Bloco 12

- [ ] `.dockerignore` criado e o `.env` não está mais na imagem
- [ ] A API roda com usuário não-root (`docker run --rm bella-tavola:v3 whoami` retorna `appuser`)
- [ ] Multi-stage build implementado e tamanho comparado
- [ ] A API v3 funciona normalmente (responde nas rotas, `/ml/predict` funciona com token)

---

## Checklist de pré-requisitos para e05-p03

Antes de avançar para o próximo caderno, confirme **todos** os itens abaixo:

- [ ] `docker compose up` sobe API + PostgreSQL + Nginx sem erros
- [ ] A API responde via Nginx em `http://localhost` (porta 80)
- [ ] `POST /ml/predict` funciona com `HF_TOKEN` passado via `env_file`
- [ ] Dados do banco persistem após `docker compose down` e `docker compose up`
- [ ] O `Dockerfile` usa usuário não-root
- [ ] O `.env` não está na imagem (`find /app -name '.env'` retorna vazio)
- [ ] Você tem conta no Docker Hub — crie em [hub.docker.com](https://hub.docker.com) se ainda não tem
- [ ] Você criou o repositório `bella-tavola` no Docker Hub
- [ ] O pipeline de CI da Semana 3 (e04) está verde no GitHub Actions

Os dois últimos itens são novos — não dependem do que foi feito neste caderno, mas são necessários para o Bloco 13. Resolva antes de começar e05-p03.

---

# Mapa do que foi construído

| Arquivo | Criado neste caderno | O que faz |
|---|---|---|
| `.dockerignore` | Bloco 12 | Lista o que não deve ser copiado para a imagem |
| `docker-compose.yml` | Bloco 11 | Orquestra API + PostgreSQL + Nginx |
| `nginx.conf` | Bloco 11 | Configuração do proxy reverso |
| `Dockerfile` | Bloco 12 (refatorado) | Agora com multi-stage build e usuário não-root |

---

# Checklist de competências — e05-p02

**Bloco 10 — Variáveis de ambiente e volumes**
- [ ] Passo o `HF_TOKEN` para o contêiner sem hardcodá-lo na imagem
- [ ] O endpoint `/ml/predict` funciona dentro do contêiner com o token
- [ ] Crio um named volume e verifico que dados persistem após recriar o contêiner
- [ ] Diferencio bind mount de named volume e sei quando usar cada um

**Bloco 11 — Docker Compose**
- [ ] Escrevo um `docker-compose.yml` com múltiplos serviços
- [ ] Entendo a diferença entre `build:` e `image:` em um serviço
- [ ] Serviços se comunicam usando o nome do serviço como hostname
- [ ] Sei a diferença entre `docker compose down` e `docker compose down -v`
- [ ] A API responde via Nginx em `http://localhost`

**Bloco 12 — Boas práticas**
- [ ] `.dockerignore` criado e o `.env` não está na imagem
- [ ] A API roda com usuário não-root dentro do contêiner
- [ ] Multi-stage build implementado e tamanho da imagem reduzido

---

## O que vem a seguir

A imagem da Bella Tavola está refinada: enxuta, segura e orquestrada com Compose. Mas ela ainda existe só na sua máquina.

Em **e05-p03**, essa imagem entra no pipeline de CI. A cada merge no `main`, se os testes passarem, a imagem é publicada automaticamente no Docker Hub. O pipeline que você construiu na Semana 3 ganha um quarto job — e a promessa do final de e04-p03 finalmente se cumpre.
"""